### PR TITLE
looks like strict option wants to be on erlef/setup-beam not top level

### PR DESCRIPTION
**Pull request by marcdel**
~🤞🏻~ 🥳

### CODE REVIEW

**Comment by marcdel** [comment]
> ## [Codecov](https://codecov.io/gh/open-telemetry/opentelemetry-erlang/pull/556?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=open-telemetry) Report
> Patch coverage has no change and project coverage change: **`-37.90`** ⚠️
> 
> > Comparison is base [(`a512334`)](https://codecov.io/gh/open-telemetry/opentelemetry-erlang/commit/a512334dba169112fe13219d91014c3120004c13?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=open-telemetry) 37.89% compared to head [(`ccf3aaa`)](https://codecov.io/gh/open-telemetry/opentelemetry-erlang/pull/556?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=open-telemetry) 0.00%.
> 
> > ❗ Current head [ccf3aaa](https://github.com/open-telemetry/opentelemetry-erlang/commit/ccf3aaa6b5dab380dec31487eb021a6ad71f0bff) differs from pull request most recent head [d9b480d](https://github.com/open-telemetry/opentelemetry-erlang/commit/d9b480ddc65188a589a8124aba30803b52df3798). Consider uploading reports for the commit [d9b480d](https://github.com/open-telemetry/opentelemetry-erlang/commit/d9b480ddc65188a589a8124aba30803b52df3798) to get more accurate results
> 
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://codecov.io/gh/open-telemetry/opentelemetry-erlang/pull/556?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=open-telemetry). 📢 Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=open-telemetry).

amend/force pushed after adding a new email so easycla would pass

**Comment by tsloughter** [comment]
Thanks! But maybe we don't need the `strict` option then?

**Comment by tsloughter** [comment]
I suppose we may as well.

But weird test failure going on.

**Comment by tsloughter** [comment]
Just to see I opened another PR doing the same change and it fails the same way. arrrrgh 

Fork your own copy of open-telemetry/opentelemetry-erlang

Code
Issues 56

**Comment by tsloughter** [comment]
Ah. It must be resetting the cache. I just did a fresh build locally and get the same errors. So its a real issue being surfaced by this change.

**Review by tsloughter — APPROVED** [review]

**Pull request merged**
