### PR TITLE
Update and delete conventions following spec

### PR DESCRIPTION
**Pull request by joaothallis**
Create following the BREAKINGs of OTEL spec

https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by tsloughter** [comment]
Cool. Was this done with the generation script? 

The app version would need to change too.

But I think this upgrade in semconv is still blocked for us by http stuff. @bryannaegele ?

I should probably try to knock that out before I start working again so we can upgrade semconv...

**Comment by joaothallis** [comment]
> Cool. Was this done with the generation script?

No, I applied the changes manually verifying the spec. Is that [this script](https://github.com/open-telemetry/opentelemetry-erlang/blob/main/apps/opentelemetry_semantic_conventions/generate.sh)?

**Comment by bryannaegele** [comment]
> But I think this upgrade in semconv is still blocked for us by http stuff. @bryannaegele ?

We still have to implement the env var checking. I don't know how we're going to deal with the new plus old. I threw out running the script, diffing, and adding deprecated stuff but that had a host of problems.

I know this is still an issue the wg knows of in general with no progress as yet. I think there are several other sigs frustrated by it.

**Comment by tsloughter** [comment]
Ugh, we have got to do something about being stuck on old semconv. Next time we meet, @bryannaegele , lets be sure to write up a detailed issue and I'll do my best to knock it out. I keep losing context on the issue and feeling like I have to start over figuring out just what to do.

**Comment by bryannaegele** [comment]
@joaothallis this is being addressed in https://github.com/open-telemetry/opentelemetry-erlang/pull/733

**Pull request closed without merging**
