### PR TITLE
Merge API and SDK

### PR DESCRIPTION
**Pull request by hauleth**
This merges two projects while maintaining edit history of the API.

Close #98

### CODE REVIEW

**Comment by tsloughter** [comment]
@hauleth nice, what command did you use to do it?

But blocked by EasyCLA which is required to merge. Everyone with a commit on the -api repo needs to sign the CLA on this repo now.

And the benchmarks run fails, but that can just be removed for the time being if its not clear how to fix.

**Comment by hauleth** [comment]
@tsloughter `git subtree add -P apps/opentelemetry_api https://github.com/open-telemetry/opentelemetry-erlang-api`

**Comment by hauleth** [comment]
@tsloughter fixed the problem with the benchmarks

We need CLA signage for this repo.

cc @zachdaniel @GregMefford @garthk @ostera

**Comment by garthk** [comment]
I signed 2020-04-06 as `garth` at `garthk.com`.

**Comment by ostera** [comment]
Signed ✍🏼! 🙌🏼

**Comment by hauleth** [comment]
@garthk are you sure you have signed CLA for this repo? Because it seems that each repo has separate CLA list.

**Comment by garthk** [comment]
Guess not. Could you point to the process?

**Comment by tsloughter** [comment]
@garthk click on the EasyCLA "Details" link in the list of checks.

**Comment by zachdaniel** [comment]
signed it :)

**Comment by GregMefford** [comment]
Signed. ✅

**Review by ferd — APPROVED** [review]

**Comment by hauleth** [comment]
@garthk https://api.lfcla.com/v2/repository-provider/github/sign/9522512/185686745/99

**Comment by tsloughter** [comment]
@hauleth did you update both the SDK and API to the latest commits after I merged a PR for each? Confused why dialyzer is failing.

**Comment by hauleth** [comment]
@tsloughter updated API, there is nothing to update in the SDK from what I see.

**Comment by tsloughter** [comment]
Oh, nm, I haven't merged it yet because stupid github actions isn't updating the checks even though it is passing, ugh.

Never know what to do when this happens. But we are waiting on @garthk anyway :)

**Comment by garthk** [comment]
Mate I'm still in my jammies eating my brekkie. I'll be on it pronto. Nag me on Slack if you haven't seen anything by an hour from now, but. :)

**Comment by tsloughter** [comment]
@garthk cool, thanks.

@hauleth I merged the PR, should just need to rebase this I guess.

**Comment by garthk** [comment]
✍️

**Review by bryannaegele — APPROVED** [review]

**Comment by bryannaegele** [comment]
With the repo merge, how are git dependencies handled/defined for each of the projects? So when pinning against a specific commit for the api, for instance, how would that be defined as a mix dependency?

**Comment by hauleth** [comment]
@bryannaegele yes, you should use sparse git dependencies.

**Comment by hauleth** [comment]
Well, due squash merge, the history went south anyway, so the whole fight about it was irrelevant.

**Comment by bryannaegele** [comment]
We could revert and re-merge :/

**Comment by hauleth** [comment]
This would require hard push to the master. I think that now it isn't worth it

**Comment by tsloughter** [comment]
Hah, dammit, derp, my bad.

**Pull request merged**
