### PR TITLE
move attribute smodule to api

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Review by ferd — APPROVED** [review]

**Comment by bryannaegele** [comment]
What's prompting the move?

**Comment by tsloughter** [comment]
@bryannaegele it was in the wrong place. Not sure why it was ever in the SDK. But motivating it to happen now is the desire to support `#attributes` as the argument to stuff like `start_span` so the user can process the Attributes only once -- whether that is to use the same attribute set in spans or in both a span, metric and log.

**Review by bryannaegele — APPROVED** [review]

**Comment by albertored** [comment]
At the moment attributes are stored (in spans and metrics ets tables) as provided by the user, should we cast them to attributes record before saving them?

**Comment by tsloughter** [comment]
@albertored not sure what you mean. In the ets table the attributes are the record.

**Comment by albertored** [comment]
@tsloughter my bad, span ETS table contains indeed attributes as records but the same is not true for metrics, there attributes are stored as raw maps. I think we should do the same for metrics (storing the record), I can open a PR for that if you think is right

**Pull request merged**
