### PR TITLE
Histogram buckets should be 1 more than boundaries

### PR DESCRIPTION
**Pull request by albertored**
Histogram buckets should be 1 more than histogram boundaries. At the moment values greater than the last boundary (let's call it `T(n)`) are accumulated in the boundary `(T(n-1), T(n)]` instead of `(T(n), +infinity)`

### CODE REVIEW

**Comment by tsloughter** [comment]
Thanks! And yea, the spec changed since this was written.

**Comment by albertored** [comment]
@tsloughter default boundaries aligned with the specification, it should be ready to be merged

**Comment by tsloughter** [comment]
Needs a changelog update.

**Comment by albertored** [comment]
@tsloughter done

**Review by ferd — APPROVED** [review]

**Review by tsloughter — APPROVED** [review]

**Pull request merged**
