### PR TITLE
Preserve a tuple attribute value

### PR DESCRIPTION
**Pull request by bullno1**
Fix https://github.com/open-telemetry/opentelemetry-erlang/issues/512

### CODE REVIEW

**Comment by tsloughter** [comment]
Uh, somehow the CLA is failing even though I already was able to merge a PR from you... hm

**Comment by bullno1** [comment]
> Uh, somehow the CLA is failing even though I already was able to merge a PR from you... hm

Missing email config from a different computer

**Comment by tsloughter** [comment]
A test needs to be updated for this change.

**Comment by tsloughter** [comment]
A test needs to be updated for this change.

**Comment by bullno1** [comment]
I also changed the `binary-list` key because that's what the caller is supposed to pass to have a binary list recorded.

**Review by tsloughter — APPROVED** [review]

**Pull request merged**
