### PR TITLE
use get_application_tracer in Elixir macros

### PR DESCRIPTION
**Pull request by tsloughter**
The Erlang macros already properly use get_application_tracer.
The reason to use get_application_tracer is the macros lookup
the tracer for the particular application by module name.

### CODE REVIEW

**Comment by tsloughter** [comment]
We should maybe just get rid of the separation between tracers registered automatically for each application and those registered by the user, and then there would be only one "get tracer" function available anyway

**Comment by indrekj** [comment]
> We should maybe just get rid of the separation between tracers registered automatically for each application and those registered by the user, and then there would be only one "get tracer" function available anyway

That would simplify things. Currently the tracers & application tracers part is quite confusing, at least to me.

**Review by indrekj — APPROVED** [review]
looks right to me, but I'll try it out in real code tomorrow

**Comment by tsloughter** [comment]
Agree it will probably confuse people.

Likely will merge this to get erlang and elixir to at least match asap and then have a PR for just getting rid of the separation.

**Review by ferd — APPROVED** [review]

**Pull request merged**
