### PR TITLE
For cumulative sums, actually accumulate

### PR DESCRIPTION
**Pull request by srstrong**

### CODE REVIEW

**Comment by tsloughter** [comment]
Thanks!

Seems to somehow break use of floats... I'm trying to debug. 

Can you also add to the `cumulative_counter` test something like:

```
    ?assertEqual(ok, otel_counter:add(Counter, 3, #{<<"c">> => <<"b">>})),
    ?assertEqual(ok, otel_counter:add(Counter, 2, #{<<"c">> => <<"b">>})),

    otel_meter_server:force_flush(),

    ?assertSumReceive(a_counter, <<"counter description">>, kb, [{23, #{<<"c">> => <<"b">>}}]),
```

at the end.

**Comment by srstrong** [comment]
Sure, will take a look at that extra test in the morning.  My system's usage is primarily with ints, so it's possible I foobar'd the float logic - will also take a look tomorrow if you've not already nailed it

**Comment by tsloughter** [comment]
So... I have no idea... I could only get it to work by doing:

```
MS = [{#sum_aggregation{key='$1',
                            start_time_unix_nano='$2',
                            last_start_time_unix_nano='_',
                            checkpoint='$5',
                            previous_checkpoint='$6',
                            int_value='$3',
                            float_value='$4'},
           [{'=:=', {element, 1, '$1'}, {const, Name}},
            {'=:=', {element, 3, '$1'}, {const, ReaderPid}},
            {'=:=', '$4', {const, 0.0}},
            {'=:=', '$6', {const, undefined}}],
           [{#sum_aggregation{key='$1',
                              start_time_unix_nano='$2',
                              last_start_time_unix_nano='$2',
                              checkpoint='$3',
                              previous_checkpoint='$5',
                              int_value=0,
                              float_value=0.0}}]},
          {#sum_aggregation{key='$1',
                            start_time_unix_nano='$2',
                            last_start_time_unix_nano='_',
                            checkpoint='$5',
                            previous_checkpoint='$6',
                            int_value='$3',
                            float_value='$4'},
           [{'=:=', {element, 1, '$1'}, {const, Name}},
            {'=:=', {element, 3, '$1'}, {const, ReaderPid}},
            {'=:=', '$6', {const, undefined}}],
           [{#sum_aggregation{key='$1',
                              start_time_unix_nano='$2',
                              last_start_time_unix_nano='$2',
                              checkpoint={'+', '$3', '$4'},
                              previous_checkpoint='$5',
                              int_value=0,
                              float_value=0.0}}]},
          {#sum_aggregation{key='$1',
                            start_time_unix_nano='$2',
                            last_start_time_unix_nano='_',
                            checkpoint='$5',
                            previous_checkpoint='$6',
                            int_value='$3',
                            float_value='$4'},
           [{'=:=', {element, 1, '$1'}, {const, Name}},
            {'=:=', {element, 3, '$1'}, {const, ReaderPid}},
            {'=:=', '$4', {const, 0.0}}],
           [{#sum_aggregation{key='$1',
                              start_time_unix_nano='$2',
                              last_start_time_unix_nano='$2',
                              checkpoint='$3',
                              previous_checkpoint={'+', '$5', '$6'},
                              int_value=0,
                              float_value=0.0}}]},
          {#sum_aggregation{key='$1',
                            start_time_unix_nano='$2',
                            last_start_time_unix_nano='_',
                            checkpoint='$5',
                            previous_checkpoint='$6',
                            int_value='$3',
                            float_value='$4'},
           [{'=:=', {element, 1, '$1'}, {const, Name}},
            {'=:=', {element, 3, '$1'}, {const, ReaderPid}}],
           [{#sum_aggregation{key='$1',
                              start_time_unix_nano='$2',
                              last_start_time_unix_nano='$2',
                              checkpoint={'+', '$3', '$4'},
                              previous_checkpoint={'+', '$5', '$6'},
                              int_value=0,
                              float_value=0.0}}]}],
    _ = ets:select_replace(Tab, MS),
```

**Comment by tsloughter** [comment]
And keeping `previous_checkpoint`'s initial value as `undefined`.

**Comment by tsloughter** [comment]
Ooooooooooooooh, nevermind. This does it:

```
aggregate(Tab, #view_aggregation{name=Name,
                                 reader=ReaderId,
                                 is_monotonic=IsMonotonic}, Value, Attributes)
  when (IsMonotonic andalso Value >= 0.0) orelse not IsMonotonic ->
    Key = {Name, Attributes, ReaderId},
    MS = [{#sum_aggregation{key=Key,
                            start_time_unix_nano='$1',
                            last_start_time_unix_nano='$5',
                            checkpoint='$2',
                            previous_checkpoint='$6',
                            int_value='$3',
                            float_value='$4'},
           [],
           [{#sum_aggregation{key={element, 2, '$_'},
                              start_time_unix_nano='$1',
                              last_start_time_unix_nano='$5',
                              checkpoint='$2',
                              previous_checkpoint='$6',
                              int_value='$3',
                              float_value={'+', '$4', {const, Value}}}}]}],
    1 =:= ets:select_replace(Tab, MS);
```

**Comment by tsloughter** [comment]
To be clear, it was trying to match when adding a float on `previous_checkpoint` being `undefined` instead of a variable value (in this case now `'$6'`). And since it never found one it always skipped the float aggregates.

**Comment by tsloughter** [comment]
@srstrong did my code make sense? I can create a PR to handle this if not.

**Comment by tsloughter** [comment]
Thanks again, resolved this with #592

**Comment by srstrong** [comment]
Great, thanks - sorry I never got around to the test etc, last week was in the US so totally ran out of time!

**Pull request closed without merging**
