### PR TITLE
and so it begins

### PR DESCRIPTION
**Pull request by tsloughter**
This is just the application skeleton to get started with.

### CODE REVIEW

**Comment by deadtrickster** [comment]
Haha I was going to do the same this Sunday :-) Glad it started. Can you also added editorconfig ?

**Comment by tsloughter** [comment]
editorconfig? I checked the opencensus-erlang repo and didn't find anything named that either.

**Comment by deadtrickster** [comment]
https://editorconfig.org/? nice thingy.

**Comment by deadtrickster** [comment]
anyway, can go in a separate PR, no problem

**Comment by tsloughter** [comment]
Ah, ok.

**Comment by tsloughter** [comment]
I signed it.

**Comment by tsloughter** [comment]
@deadtrickster can you mark as approved? It requires at least 1 review to merge.

**Pull request merged**
